CREATE TABLE formatted_data (
	"unix_time" DOUBLE PRECISION,
	"u_year" DOUBLE PRECISION,
	"u_month" DOUBLE PRECISION,
	"u_day" DOUBLE PRECISION,
	"u_hour" DOUBLE PRECISION,
	"u_minute" DOUBLE PRECISION,
	"u_second" DOUBLE PRECISION,
	"clock_source" text,
	"stardate" DOUBLE PRECISION,
	"future_time" DOUBLE PRECISION, --
	"geiger_ticks" DOUBLE PRECISION,
	"geiger_high_volts" DOUBLE PRECISION,
	"geiger_current" DOUBLE PRECISION,
	"geiger_temperature" DOUBLE PRECISION,
	"geiger_status" text, --
	"vortex_avg_speed" DOUBLE PRECISION,
	"vortex_wind_gust" DOUBLE PRECISION,
	"vortex_calc_mph" DOUBLE PRECISION, --
	"rain_drip_code" text,
	"rain_bucket" DOUBLE PRECISION,
	"rain_rate" DOUBLE PRECISION,
	"rain_ten_min_dry" DOUBLE PRECISION,
	"rain_battery_voltage" text, --
	"RTD_1K_upper" DOUBLE PRECISION,
	"RTD_1K_middle" DOUBLE PRECISION,
	"RTD_1K_lower" DOUBLE PRECISION,
	"RTD_100_upper" DOUBLE PRECISION,
	"RTD_100_middle" DOUBLE PRECISION,
	"RTD_100_lower" DOUBLE PRECISION,
	"RTD_Davis_upper" DOUBLE PRECISION,
	"RTD_Davis_middle" DOUBLE PRECISION,
	"RTD_Davis_lower" DOUBLE PRECISION,
	"RH_sensor_1" DOUBLE PRECISION,
	"RH_sensor_2" DOUBLE PRECISION,
	"outer_shield_LM335" DOUBLE PRECISION,
	"middle_shield_LM335" DOUBLE PRECISION,
	"inner_shield_LM335" DOUBLE PRECISION,
	"bowl_LM335" DOUBLE PRECISION,
	"ambient_temp_LM335" DOUBLE PRECISION,
	"IR_snow_depth" DOUBLE PRECISION,
	"temp_head_fan_airflow" DOUBLE PRECISION,
	"temp_head_fan_voltage" DOUBLE PRECISION,
	"temp_head_fan_current" DOUBLE PRECISION,
	"PTB_upper" DOUBLE PRECISION,
	"PTB_middle" DOUBLE PRECISION,
	"PTB_lower" DOUBLE PRECISION,
	"AD_temperature" DOUBLE PRECISION, --
	"fan_voltage" DOUBLE PRECISION,
	"fan_current" DOUBLE PRECISION,
	"fan_speed" DOUBLE PRECISION,
	"Arduino_teensy_current" DOUBLE PRECISION,
	"RF_link_current" DOUBLE PRECISION,
	"box_humidity" DOUBLE PRECISION,
	"ground_temperature" DOUBLE PRECISION, --
	"snow_depth_sonic" DOUBLE PRECISION,
	"barometric_pressure" DOUBLE PRECISION,
	"ten_enclosure_temp" DOUBLE PRECISION,
	"ten_circuit_current" DOUBLE PRECISION,
	"ten_RTD_temperature" DOUBLE PRECISION,
	"RH_Precon" DOUBLE PRECISION,
	"Temperature_Precon" DOUBLE PRECISION,
	"RH_Honeywell" DOUBLE PRECISION,
	"ten_avg_wind_speed" DOUBLE PRECISION,
	"ten_instant_wind_speed" DOUBLE PRECISION,
	"ten_wind_direction" DOUBLE PRECISION, --
	"power_100WA_voltage" DOUBLE PRECISION,
	"power_100WA_current" DOUBLE PRECISION,
	"power_100WB_voltage" DOUBLE PRECISION,
	"power_100WB_current" DOUBLE PRECISION,
	"power_50W_voltage" DOUBLE PRECISION,
	"power_50W_current" DOUBLE PRECISION,
	"power_20WA_voltage" DOUBLE PRECISION,
	"power_20WA_current" DOUBLE PRECISION,
	"power_load_voltage" DOUBLE PRECISION,
	"power_load_current" DOUBLE PRECISION,
	"power_battery_voltage" DOUBLE PRECISION,
	"power_battery_current" DOUBLE PRECISION,
	"power_solar_voltage" DOUBLE PRECISION,
	"power_solar_current" DOUBLE PRECISION,
	"power_20WB_voltage" DOUBLE PRECISION,
	"power_20WB_current" DOUBLE PRECISION,
	"power_fan_current_A" DOUBLE PRECISION,
	"power_heater_current_A" DOUBLE PRECISION,
	"power_battery_temperature_A" DOUBLE PRECISION,
	"power_cabinet_temperature" DOUBLE PRECISION,
	"power_MPPT_temperature" DOUBLE PRECISION,
	"power_5C_voltage" DOUBLE PRECISION,
	"power_5DAQ_voltage" DOUBLE PRECISION,
	"power_5DAQ_current" DOUBLE PRECISION,
	"power_VTOP_voltage" DOUBLE PRECISION,
	"power_VTOP_current" DOUBLE PRECISION,
	"power_VAUX_voltage" DOUBLE PRECISION,
	"power_VAUX_current" DOUBLE PRECISION,
	"power_DAQ_input_current" DOUBLE PRECISION,
	"power_battery_temperature_B" DOUBLE PRECISION,
	"power_box_temperature" DOUBLE PRECISION,
	"power_heater_current_B" DOUBLE PRECISION,
	"power_fan_current_B" DOUBLE PRECISION,
	"power_status" text,
	"power_enclosure_humidity" DOUBLE PRECISION,
	"power_fault_status" text, --
	"soil_temp_1_below" DOUBLE PRECISION,
	"soil_temp_2_below" DOUBLE PRECISION,
	"soil_temp_3_below" DOUBLE PRECISION,
	"soil_temp_4_below" DOUBLE PRECISION,
	"soil_temp_5_below" DOUBLE PRECISION,
	"soil_temp_6_below" DOUBLE PRECISION,
	"soil_temp_7_below" DOUBLE PRECISION,
	"soil_temp_8_below" DOUBLE PRECISION,
	"soil_temp_10_below" DOUBLE PRECISION,
	"soil_temp_12_below" DOUBLE PRECISION,
	"soil_temp_20_below" DOUBLE PRECISION,
	"soil_temp_30_below" DOUBLE PRECISION,
	"soil_temp_40_below" DOUBLE PRECISION,
	"soil_temp_48_below" DOUBLE PRECISION, --
	"soil_moist_b2" DOUBLE PRECISION,
	"soil_moist_b4" DOUBLE PRECISION,
	"soil_moist_b6" DOUBLE PRECISION,
	"soil_moist_b8" DOUBLE PRECISION,
	"soil_moist_b10" DOUBLE PRECISION,
	"soil_moist_b15" DOUBLE PRECISION,
	"soil_moist_b20" DOUBLE PRECISION,
	"soil_moist_b40" DOUBLE PRECISION, --
	"temp_1_above" DOUBLE PRECISION,
	"temp_2_above" DOUBLE PRECISION,
	"temp_3_above" DOUBLE PRECISION,
	"temp_4_above" DOUBLE PRECISION,
	"temp_5_above" DOUBLE PRECISION,
	"temp_7_above" DOUBLE PRECISION,
	"temp_9_above" DOUBLE PRECISION,
	"temp_11_above" DOUBLE PRECISION,
	"temp_13_above" DOUBLE PRECISION,
	"temp_15_above" DOUBLE PRECISION, --
	"soil_flux" DOUBLE PRECISION,
	"soil_electronics_temp" DOUBLE PRECISION,
	"soil_electronics_Vref" DOUBLE PRECISION,
	"soil_spare" DOUBLE PRECISION, --
	"Geiger_burst_count" DOUBLE PRECISION,
	"Geiger_burst_time" DOUBLE PRECISION,
	"barometric_temperature" DOUBLE PRECISION, --
	"load_dcdc_voltage_input" DOUBLE PRECISION,
	"load_dcdc_current_input" DOUBLE PRECISION,
	"load_dcdc_current_output" DOUBLE PRECISION,
	"load_dcdc_voltage_output" DOUBLE PRECISION,
	"battery_charger_current_input" DOUBLE PRECISION,
	"battery_charger_current_output" DOUBLE PRECISION,
	"battery_charger_temperature" DOUBLE PRECISION,
	"battery_charger_voltage_output" DOUBLE PRECISION,
	"solar_dcdc_input_voltage" DOUBLE PRECISION,
	"solar_dcdc_input_current" DOUBLE PRECISION,
	"solar_charger_current_output" DOUBLE PRECISION,
	"solar_charger_voltage_output" DOUBLE PRECISION,
	"load_voltage" DOUBLE PRECISION,
	"battery_voltage" DOUBLE PRECISION,
	"battery_temperature" DOUBLE PRECISION,
	"battery_protection_status" text,
	"weatherproof_enclosure_temperature" DOUBLE PRECISION,
	"power_supply_box_temperature" DOUBLE PRECISION,
	"power_supply_humidity" DOUBLE PRECISION,
	"V30_supply_fan_speed" DOUBLE PRECISION,
	"V30_supply_fan_current" DOUBLE PRECISION,
	"V30_supply_current_output" DOUBLE PRECISION,
	"V30_supply_voltage_output" DOUBLE PRECISION,
	"V30_supply_24V_supply_voltage" DOUBLE PRECISION,
	"V30_converter_board_current_input" DOUBLE PRECISION,
	"V30_converter_board_voltage_input" DOUBLE PRECISION,
	"MOSFET_switches_status" text,
	"protection_raw_voltage" DOUBLE PRECISION,
	"protection_protected_voltage" DOUBLE PRECISION,
	"protection_raw_input_current" DOUBLE PRECISION,
	"protection_circuit_status" text, --
	"mux_current" DOUBLE PRECISION,
	"mux_temperature" DOUBLE PRECISION,
	"Peet_wind_rate" DOUBLE PRECISION,
	"Peet_wind_multl" DOUBLE PRECISION,
	"Peet_windlo" DOUBLE PRECISION,
	"Peet_wind_multh" DOUBLE PRECISION,
	"Peet_windhi" DOUBLE PRECISION,
	"Peet_vduce" DOUBLE PRECISION,
	"Peet_winddir" DOUBLE PRECISION,
	"Inspeed_wind_direction" DOUBLE PRECISION,
	"Hydreon_current" DOUBLE PRECISION,
	"Hydreon_temperature" DOUBLE PRECISION,
	"Hydreon_range_setting" text,
	"Hydreon_low_sense" DOUBLE PRECISION,
	"Hydreon_medium_sense" DOUBLE PRECISION,
	"Hydreon_high_sense" DOUBLE PRECISION,
	"sky_sensor_current" DOUBLE PRECISION,
	"sky_swiper_CW_current" DOUBLE PRECISION,
	"sky_swiper_CCW_current" DOUBLE PRECISION,
	"sky_dark_reading" DOUBLE PRECISION,
	"sky_bright_reading" DOUBLE PRECISION,
	"sky_IR_temperature" DOUBLE PRECISION,
	"sky_sensor_status" text,
	"sky_Hall_sensor" DOUBLE PRECISION,
	"sway_X40_reading" DOUBLE PRECISION,
	"sway_X1_reading" DOUBLE PRECISION,
	"sway_Y1_reading" DOUBLE PRECISION,
	"sway_Y40_reading" DOUBLE PRECISION,
	"sway_sensor_temperature" DOUBLE PRECISION,
	"sway_sensor_Vss" DOUBLE PRECISION,
	"sway_Z_offset" DOUBLE PRECISION,
	"sway_Z50_reading" DOUBLE PRECISION,
	"lightning_current" DOUBLE PRECISION,
	"lightning_UV_count" DOUBLE PRECISION,
	"lightning_high_voltage" DOUBLE PRECISION,
	"lightning_3001_lux" DOUBLE PRECISION,
	"lightning_Skyscan_current" DOUBLE PRECISION,
	"lightning_Skyscan_LEDs" text,
	"lightning_Skyscan_flash_time" DOUBLE PRECISION,
	"lightning_Skyscan_alarms" text,
	"lightning_OPT101_baseline" DOUBLE PRECISION,
	"lightning_OPT101_north" DOUBLE PRECISION,
	"lightning_OPT101_south" DOUBLE PRECISION,
	"lightning_OPT101_east" DOUBLE PRECISION,
	"lightning_OPT101_west" DOUBLE PRECISION,
	"lightning_OPT101_zenith" DOUBLE PRECISION,
	"lightning_thunder" DOUBLE PRECISION,
	"lightning_flag" text,
	"lightning_UVA_UVB" DOUBLE PRECISION,
	"lightning_OPT_temperature" DOUBLE PRECISION, --
	"solar_box_temperature" DOUBLE PRECISION,
	"solar_pyran_upper_byte" DOUBLE PRECISION,
	"solar_pyran_middle_byte" DOUBLE PRECISION,
	"solar_pyran_lower_byte" DOUBLE PRECISION,
	"solar_par_upper_byte" DOUBLE PRECISION,
	"solar_par_middle_byte" DOUBLE PRECISION,
	"solar_par_lower_byte" DOUBLE PRECISION,
	"solar_UV_upper_byte" DOUBLE PRECISION,
	"solar_UV_middle_byte" DOUBLE PRECISION,
	"solar_UV_lower_byte" DOUBLE PRECISION,
	"solar_gold_grid_east" DOUBLE PRECISION,
	"solar_gold_grid_west" DOUBLE PRECISION,
	"solar_Decagon_horizontal" DOUBLE PRECISION,
	"solar_Decagon_tilted" DOUBLE PRECISION,
	"solar_frost" DOUBLE PRECISION,
	"solar_bud" DOUBLE PRECISION,
	"solar_globe_upper_byte" DOUBLE PRECISION,
	"solar_globe_middle_byte" DOUBLE PRECISION,
	"solar_globe_lower_byte" DOUBLE PRECISION,
	"solar_current" DOUBLE PRECISION,
	"solar_voltage" DOUBLE PRECISION,
	"solar_IR_ground_temperature" DOUBLE PRECISION, --
	"MetOne_LED_current" DOUBLE PRECISION,
	"MetOne_wind_speed_average" DOUBLE PRECISION,
	"MetOne_wind_speed_gust" DOUBLE PRECISION, --
	"fuses_Arbcam_current" DOUBLE PRECISION,
	"fuses_Arbcam_voltage" DOUBLE PRECISION,
	"fuses_5_6_voltage" DOUBLE PRECISION,
	"fuses_mux_current" DOUBLE PRECISION,
	"fuses_lightning_current" DOUBLE PRECISION,
	"fuses_solar_DAQ_current" DOUBLE PRECISION,
	"fuses_fluxgate_current" DOUBLE PRECISION,
	"fuses_triaxial_current" DOUBLE PRECISION,
	"fuses_future_current" DOUBLE PRECISION,
	"fuses_flag" text,
	"fuses_warn" text,
	"fuses_go_up" text,
	"fuses_monitor" text,
	"fuses_Arbcam_mode" text,
	"fuses_fault_status" text, --
	"power_solar_panel_current" DOUBLE PRECISION,
	"power_solar_panel_voltage" DOUBLE PRECISION,
	"power_battery_current_B" DOUBLE PRECISION,
	"power_battery_voltage_B" DOUBLE PRECISION,
	"power_current_into_5_6" DOUBLE PRECISION,
	"power_voltage_into_5_6" DOUBLE PRECISION,
	"power_5_6_load_current" DOUBLE PRECISION,
	"power_5_6_load_voltage" DOUBLE PRECISION,
	"power_box_temperature_B" DOUBLE PRECISION,
	"power_Arbcam_dcdc_input_current" DOUBLE PRECISION,
	"power_Arbcam_dcdc_input_voltage" DOUBLE PRECISION,
	"power_Arbcam_current" DOUBLE PRECISION,
	"power_Arbcam_voltage" DOUBLE PRECISION,
	"power_battery_temperature" DOUBLE PRECISION,
	"power_128K_battery_voltage" DOUBLE PRECISION,
	"power_RTC_battery_voltage" DOUBLE PRECISION,
	"power_RTD_30ft_temperature" DOUBLE PRECISION,
	"power_hail_peak" DOUBLE PRECISION,
	"power_hail_average" DOUBLE PRECISION,
	"power_status_B" text,
	"power_OVP_cycles" DOUBLE PRECISION,
	"power_OVP_voltage" DOUBLE PRECISION,
	"power_hail_sensor_temperature" DOUBLE PRECISION,
	"power_hail_sensor_hits" DOUBLE PRECISION,
	"power_box_humidity" DOUBLE PRECISION, --
	"s_X1" DOUBLE PRECISION,
	"s_X2" DOUBLE PRECISION,
	"s_X3" DOUBLE PRECISION,
	"s_X4" DOUBLE PRECISION,
	"s_X5" DOUBLE PRECISION,
	"s_X6" DOUBLE PRECISION,
	"s_X7" DOUBLE PRECISION,
	"s_X8" DOUBLE PRECISION,
	"s_X9" DOUBLE PRECISION,
	"s_X10" DOUBLE PRECISION,
	"s_X11" DOUBLE PRECISION,
	"s_X12" DOUBLE PRECISION,
	"s_X13" DOUBLE PRECISION,
	"s_X14" DOUBLE PRECISION,
	"s_X15" DOUBLE PRECISION,
	"s_X16" DOUBLE PRECISION,
	"s_X17" DOUBLE PRECISION,
	"s_X18" DOUBLE PRECISION,
	"s_X19" DOUBLE PRECISION,
	"s_X20" DOUBLE PRECISION,
	"s_X21" DOUBLE PRECISION,
	"s_X22" DOUBLE PRECISION,
	"s_X23" DOUBLE PRECISION,
	"s_X24" DOUBLE PRECISION,
	"s_X25" DOUBLE PRECISION,
	"s_X26" DOUBLE PRECISION,
	"s_X27" DOUBLE PRECISION,
	"s_X28" DOUBLE PRECISION,
	"s_X29" DOUBLE PRECISION,
	"s_X30" DOUBLE PRECISION,
	"s_X31" DOUBLE PRECISION,
	"s_X32" DOUBLE PRECISION,
	"s_X33" DOUBLE PRECISION,
	"s_X34" DOUBLE PRECISION,
	"s_X35" DOUBLE PRECISION,
	"s_X36" DOUBLE PRECISION,
	"s_X37" DOUBLE PRECISION,
	"s_X38" DOUBLE PRECISION,
	"s_X39" DOUBLE PRECISION,
	"s_X40" DOUBLE PRECISION, --
	"s_Y1" DOUBLE PRECISION,
	"s_Y2" DOUBLE PRECISION,
	"s_Y3" DOUBLE PRECISION,
	"s_Y4" DOUBLE PRECISION,
	"s_Y5" DOUBLE PRECISION,
	"s_Y6" DOUBLE PRECISION,
	"s_Y7" DOUBLE PRECISION,
	"s_Y8" DOUBLE PRECISION,
	"s_Y9" DOUBLE PRECISION,
	"s_Y10" DOUBLE PRECISION,
	"s_Y11" DOUBLE PRECISION,
	"s_Y12" DOUBLE PRECISION,
	"s_Y13" DOUBLE PRECISION,
	"s_Y14" DOUBLE PRECISION,
	"s_Y15" DOUBLE PRECISION,
	"s_Y16" DOUBLE PRECISION,
	"s_Y17" DOUBLE PRECISION,
	"s_Y18" DOUBLE PRECISION,
	"s_Y19" DOUBLE PRECISION,
	"s_Y20" DOUBLE PRECISION,
	"s_Y21" DOUBLE PRECISION,
	"s_Y22" DOUBLE PRECISION,
	"s_Y23" DOUBLE PRECISION,
	"s_Y24" DOUBLE PRECISION,
	"s_Y25" DOUBLE PRECISION,
	"s_Y26" DOUBLE PRECISION,
	"s_Y27" DOUBLE PRECISION,
	"s_Y28" DOUBLE PRECISION,
	"s_Y29" DOUBLE PRECISION,
	"s_Y30" DOUBLE PRECISION,
	"s_Y31" DOUBLE PRECISION,
	"s_Y32" DOUBLE PRECISION,
	"s_Y33" DOUBLE PRECISION,
	"s_Y34" DOUBLE PRECISION,
	"s_Y35" DOUBLE PRECISION,
	"s_Y36" DOUBLE PRECISION,
	"s_Y37" DOUBLE PRECISION,
	"s_Y38" DOUBLE PRECISION,
	"s_Y39" DOUBLE PRECISION,
	"s_Y40" DOUBLE PRECISION, --
	"f_T1" DOUBLE PRECISION,
	"f_X1" DOUBLE PRECISION,
	"f_Y1" DOUBLE PRECISION,
	"f_Z1" DOUBLE PRECISION,
	"f_T2" DOUBLE PRECISION,
	"f_X2" DOUBLE PRECISION,
	"f_Y2" DOUBLE PRECISION,
	"f_Z2" DOUBLE PRECISION,
	"f_T3" DOUBLE PRECISION,
	"f_X3" DOUBLE PRECISION,
	"f_Y3" DOUBLE PRECISION,
	"f_Z3" DOUBLE PRECISION,
	"f_T4" DOUBLE PRECISION,
	"f_X4" DOUBLE PRECISION,
	"f_Y4" DOUBLE PRECISION,
	"f_Z4" DOUBLE PRECISION,
	"f_T5" DOUBLE PRECISION,
	"f_X5" DOUBLE PRECISION,
	"f_Y5" DOUBLE PRECISION,
	"f_Z5" DOUBLE PRECISION,
	"f_T6" DOUBLE PRECISION,
	"f_X6" DOUBLE PRECISION,
	"f_Y6" DOUBLE PRECISION,
	"f_Z6" DOUBLE PRECISION,
	"f_T7" DOUBLE PRECISION,
	"f_X7" DOUBLE PRECISION,
	"f_Y7" DOUBLE PRECISION,
	"f_Z7" DOUBLE PRECISION,
	"f_T8" DOUBLE PRECISION,
	"f_X8" DOUBLE PRECISION,
	"f_Y8" DOUBLE PRECISION,
	"f_Z8" DOUBLE PRECISION,
	"f_T9" DOUBLE PRECISION,
	"f_X9" DOUBLE PRECISION,
	"f_Y9" DOUBLE PRECISION,
	"f_Z9" DOUBLE PRECISION,
	"f_T10" DOUBLE PRECISION,
	"f_X10" DOUBLE PRECISION,
	"f_Y10" DOUBLE PRECISION,
	"f_Z10" DOUBLE PRECISION,
	"f_T11" DOUBLE PRECISION,
	"f_X11" DOUBLE PRECISION,
	"f_Y11" DOUBLE PRECISION,
	"f_Z11" DOUBLE PRECISION,
	"f_T12" DOUBLE PRECISION,
	"f_X12" DOUBLE PRECISION,
	"f_Y12" DOUBLE PRECISION,
	"f_Z12" DOUBLE PRECISION,
	"f_T13" DOUBLE PRECISION,
	"f_X13" DOUBLE PRECISION,
	"f_Y13" DOUBLE PRECISION,
	"f_Z13" DOUBLE PRECISION,
	"f_T14" DOUBLE PRECISION,
	"f_X14" DOUBLE PRECISION,
	"f_Y14" DOUBLE PRECISION,
	"f_Z14" DOUBLE PRECISION, --
	"fluxgate_current" DOUBLE PRECISION,
	"fluxgate_temperature" DOUBLE PRECISION,
	"fluxgate_xset" DOUBLE PRECISION,
	"fluxgate_yset" DOUBLE PRECISION,
	"fluxgate_zset" DOUBLE PRECISION,
	"fluxgate_flag" text, --
	"t_T1" DOUBLE PRECISION,
	"t_X1" DOUBLE PRECISION,
	"t_Y1" DOUBLE PRECISION,
	"t_Z1" DOUBLE PRECISION,
	"t_T2" DOUBLE PRECISION,
	"t_X2" DOUBLE PRECISION,
	"t_Y2" DOUBLE PRECISION,
	"t_Z2" DOUBLE PRECISION,
	"t_T3" DOUBLE PRECISION,
	"t_X3" DOUBLE PRECISION,
	"t_Y3" DOUBLE PRECISION,
	"t_Z3" DOUBLE PRECISION,
	"t_T4" DOUBLE PRECISION,
	"t_X4" DOUBLE PRECISION,
	"t_Y4" DOUBLE PRECISION,
	"t_Z4" DOUBLE PRECISION,
	"t_T5" DOUBLE PRECISION,
	"t_X5" DOUBLE PRECISION,
	"t_Y5" DOUBLE PRECISION,
	"t_Z5" DOUBLE PRECISION,
	"t_T6" DOUBLE PRECISION,
	"t_X6" DOUBLE PRECISION,
	"t_Y6" DOUBLE PRECISION,
	"t_Z6" DOUBLE PRECISION,
	"t_T7" DOUBLE PRECISION,
	"t_X7" DOUBLE PRECISION,
	"t_Y7" DOUBLE PRECISION,
	"t_Z7" DOUBLE PRECISION,
	"t_T8" DOUBLE PRECISION,
	"t_X8" DOUBLE PRECISION,
	"t_Y8" DOUBLE PRECISION,
	"t_Z8" DOUBLE PRECISION,
	"t_T9" DOUBLE PRECISION,
	"t_X9" DOUBLE PRECISION,
	"t_Y9" DOUBLE PRECISION,
	"t_Z9" DOUBLE PRECISION,
	"t_T10" DOUBLE PRECISION,
	"t_X10" DOUBLE PRECISION,
	"t_Y10" DOUBLE PRECISION,
	"t_Z10" DOUBLE PRECISION,
	"t_T11" DOUBLE PRECISION,
	"t_X11" DOUBLE PRECISION,
	"t_Y11" DOUBLE PRECISION,
	"t_Z11" DOUBLE PRECISION,
	"t_T12" DOUBLE PRECISION,
	"t_X12" DOUBLE PRECISION,
	"t_Y12" DOUBLE PRECISION,
	"t_Z12" DOUBLE PRECISION,
	"t_T13" DOUBLE PRECISION,
	"t_X13" DOUBLE PRECISION,
	"t_Y13" DOUBLE PRECISION,
	"t_Z13" DOUBLE PRECISION,
	"t_T14" DOUBLE PRECISION,
	"t_X14" DOUBLE PRECISION,
	"t_Y14" DOUBLE PRECISION,
	"t_Z14" DOUBLE PRECISION,
	"t_T15" DOUBLE PRECISION,
	"t_X15" DOUBLE PRECISION,
	"t_Y15" DOUBLE PRECISION,
	"t_Z15" DOUBLE PRECISION,
	"t_T16" DOUBLE PRECISION,
	"t_X16" DOUBLE PRECISION,
	"t_Y16" DOUBLE PRECISION,
	"t_Z16" DOUBLE PRECISION,
	"t_T17" DOUBLE PRECISION,
	"t_X17" DOUBLE PRECISION,
	"t_Y17" DOUBLE PRECISION,
	"t_Z17" DOUBLE PRECISION,
	"t_T18" DOUBLE PRECISION,
	"t_X18" DOUBLE PRECISION,
	"t_Y18" DOUBLE PRECISION,
	"t_Z18" DOUBLE PRECISION,
	"t_T19" DOUBLE PRECISION,
	"t_X19" DOUBLE PRECISION,
	"t_Y19" DOUBLE PRECISION,
	"t_Z19" DOUBLE PRECISION,
	"t_T20" DOUBLE PRECISION,
	"t_X20" DOUBLE PRECISION,
	"t_Y20" DOUBLE PRECISION,
	"t_Z20" DOUBLE PRECISION, --
	"triaxial_current" DOUBLE PRECISION,
	"triaxial_volts" DOUBLE PRECISION,
	"triaxial_temperature" DOUBLE PRECISION, --
	"PurpleAir_dcdc_current_input" DOUBLE PRECISION,
	"PurpleAir_dcdc_current_output" DOUBLE PRECISION,
	"PurpleAir_dcdc_voltage" DOUBLE PRECISION, --
	"Particles_dcdc_current_input" DOUBLE PRECISION,
	"Particles_dcdc_current_output" DOUBLE PRECISION,
	"Particles_dcdc_voltage" DOUBLE PRECISION,
	"Particles_dcdc_temperature" DOUBLE PRECISION,
	"Aux_box_fans_voltage" DOUBLE PRECISION, --
	"Aux_B_dcdc_current_input" DOUBLE PRECISION,
	"Aux_B_dcdc_current_output" DOUBLE PRECISION,
	"Aux_B_dcdc_voltage" DOUBLE PRECISION, --
	"Aux_A_dcdc_current_input" DOUBLE PRECISION,
	"Aux_A_dcdc_current_output" DOUBLE PRECISION,
	"Aux_A_dcdc_voltage" DOUBLE PRECISION,
	"Aux_A_dcdc_temperature" DOUBLE PRECISION,
	"Aux_A_spare" DOUBLE PRECISION, --
	"Schumann_dcdc_current_input" DOUBLE PRECISION,
	"Schumann_dcdc_current_output" DOUBLE PRECISION,
	"Schumann_dcdc_voltage" DOUBLE PRECISION, --
	"CFLUX_1_dcdc_current_input" DOUBLE PRECISION,
	"CFLUX_1_dcdc_current_output" DOUBLE PRECISION,
	"CFLUX_1_dcdc_voltage" DOUBLE PRECISION,
	"CFLUX_spare_1" DOUBLE PRECISION,
	"CFLUX_spare_2" DOUBLE PRECISION, --
	"Aux_box_input_current" DOUBLE PRECISION,
	"Aux_box_input_voltage" DOUBLE PRECISION,
	"fiber_optic_link_dcdc_current_input" DOUBLE PRECISION,
	"fiber_optic_link_dcdc_voltage_input" DOUBLE PRECISION,
	"USB_jack_dcdc_current_input" DOUBLE PRECISION,
	"USB_jack_dcdc_voltage_input" DOUBLE PRECISION,
	"USB_dcdc_temperature" DOUBLE PRECISION,
	"fans_current" DOUBLE PRECISION,
	"fan_A_speed" DOUBLE PRECISION,
	"fan_B_speed" DOUBLE PRECISION,
	"fan_C_speed" DOUBLE PRECISION,
	"Aux_box_humidity" DOUBLE PRECISION,
	"Aux_box_fan_status" text,
	"Aux_box_MOSFET_status" text,
	"Aux_box_fuse_status" text,
	"Aux_box_over_current_status" text,

	id BIGSERIAL PRIMARY KEY NOT NULL,
	datetime_utc TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAUlT CURRENT_TIMESTAMP(0),

	-- Not including time so column indices will be 10 less than in formatted_data
	-- 0: N/A either formatted_data column is NULL or no specified range
	-- 1: below range of expected values
	-- 2: in range of expected values
	-- 3: above range of expected values
	"geiger_ticks_range" SMALLINT,
	"geiger_high_volts_range" SMALLINT,
	"geiger_current_range" SMALLINT,
	"geiger_temperature_range" SMALLINT,
	"geiger_status_range" SMALLINT, --
	"vortex_avg_speed_range" SMALLINT,
	"vortex_wind_gust_range" SMALLINT,
	"vortex_calc_mph_range" SMALLINT, --
	"rain_drip_code_range" SMALLINT,
	"rain_bucket_range" SMALLINT,
	"rain_rate_range" SMALLINT,
	"rain_ten_min_dry_range" SMALLINT,
	"rain_battery_voltage_range" SMALLINT, --
	"RTD_1K_upper_range" SMALLINT,
	"RTD_1K_middle_range" SMALLINT,
	"RTD_1K_lower_range" SMALLINT,
	"RTD_100_upper_range" SMALLINT,
	"RTD_100_middle_range" SMALLINT,
	"RTD_100_lower_range" SMALLINT,
	"RTD_Davis_upper_range" SMALLINT,
	"RTD_Davis_middle_range" SMALLINT,
	"RTD_Davis_lower_range" SMALLINT,
	"RH_sensor_1_range" SMALLINT,
	"RH_sensor_2_range" SMALLINT,
	"outer_shield_LM335_range" SMALLINT,
	"middle_shield_LM335_range" SMALLINT,
	"inner_shield_LM335_range" SMALLINT,
	"bowl_LM335_range" SMALLINT,
	"ambient_temp_LM335_range" SMALLINT,
	"IR_snow_depth_range" SMALLINT,
	"temp_head_fan_airflow_range" SMALLINT,
	"temp_head_fan_voltage_range" SMALLINT,
	"temp_head_fan_current_range" SMALLINT,
	"PTB_upper_range" SMALLINT,
	"PTB_middle_range" SMALLINT,
	"PTB_lower_range" SMALLINT,
	"AD_temperature_range" SMALLINT, --
	"fan_voltage_range" SMALLINT,
	"fan_current_range" SMALLINT,
	"fan_speed_range" SMALLINT,
	"Arduino_teensy_current_range" SMALLINT,
	"RF_link_current_range" SMALLINT,
	"box_humidity_range" SMALLINT,
	"ground_temperature_range" SMALLINT, --
	"snow_depth_sonic_range" SMALLINT,
	"barometric_pressure_range" SMALLINT,
	"ten_enclosure_temp_range" SMALLINT,
	"ten_circuit_current_range" SMALLINT,
	"ten_RTD_temperature_range" SMALLINT,
	"RH_Precon_range" SMALLINT,
	"Temperature_Precon_range" SMALLINT,
	"RH_Honeywell_range" SMALLINT,
	"ten_avg_wind_speed_range" SMALLINT,
	"ten_instant_wind_speed_range" SMALLINT,
	"ten_wind_direction_range" SMALLINT, --
	"power_100WA_voltage_range" SMALLINT,
	"power_100WA_current_range" SMALLINT,
	"power_100WB_voltage_range" SMALLINT,
	"power_100WB_current_range" SMALLINT,
	"power_50W_voltage_range" SMALLINT,
	"power_50W_current_range" SMALLINT,
	"power_20WA_voltage_range" SMALLINT,
	"power_20WA_current_range" SMALLINT,
	"power_load_voltage_range" SMALLINT,
	"power_load_current_range" SMALLINT,
	"power_battery_voltage_range" SMALLINT,
	"power_battery_current_range" SMALLINT,
	"power_solar_voltage_range" SMALLINT,
	"power_solar_current_range" SMALLINT,
	"power_20WB_voltage_range" SMALLINT,
	"power_20WB_current_range" SMALLINT,
	"power_fan_current_A_range" SMALLINT,
	"power_heater_current_A_range" SMALLINT,
	"power_battery_temperature_A_range" SMALLINT,
	"power_cabinet_temperature_range" SMALLINT,
	"power_MPPT_temperature_range" SMALLINT,
	"power_5C_voltage_range" SMALLINT,
	"power_5DAQ_voltage_range" SMALLINT,
	"power_5DAQ_current_range" SMALLINT,
	"power_VTOP_voltage_range" SMALLINT,
	"power_VTOP_current_range" SMALLINT,
	"power_VAUX_voltage_range" SMALLINT,
	"power_VAUX_current_range" SMALLINT,
	"power_DAQ_input_current_range" SMALLINT,
	"power_battery_temperature_B_range" SMALLINT,
	"power_box_temperature_range" SMALLINT,
	"power_heater_current_B_range" SMALLINT,
	"power_fan_current_B_range" SMALLINT,
	"power_status_range" SMALLINT,
	"power_enclosure_humidity_range" SMALLINT,
	"power_fault_status_range" SMALLINT, --
	"soil_temp_1_below_range" SMALLINT,
	"soil_temp_2_below_range" SMALLINT,
	"soil_temp_3_below_range" SMALLINT,
	"soil_temp_4_below_range" SMALLINT,
	"soil_temp_5_below_range" SMALLINT,
	"soil_temp_6_below_range" SMALLINT,
	"soil_temp_7_below_range" SMALLINT,
	"soil_temp_8_below_range" SMALLINT,
	"soil_temp_10_below_range" SMALLINT,
	"soil_temp_12_below_range" SMALLINT,
	"soil_temp_20_below_range" SMALLINT,
	"soil_temp_30_below_range" SMALLINT,
	"soil_temp_40_below_range" SMALLINT,
	"soil_temp_48_below_range" SMALLINT, --
	"soil_moist_b2_range" SMALLINT,
	"soil_moist_b4_range" SMALLINT,
	"soil_moist_b6_range" SMALLINT,
	"soil_moist_b8_range" SMALLINT,
	"soil_moist_b10_range" SMALLINT,
	"soil_moist_b15_range" SMALLINT,
	"soil_moist_b20_range" SMALLINT,
	"soil_moist_b40_range" SMALLINT, --
	"temp_1_above_range" SMALLINT,
	"temp_2_above_range" SMALLINT,
	"temp_3_above_range" SMALLINT,
	"temp_4_above_range" SMALLINT,
	"temp_5_above_range" SMALLINT,
	"temp_7_above_range" SMALLINT,
	"temp_9_above_range" SMALLINT,
	"temp_11_above_range" SMALLINT,
	"temp_13_above_range" SMALLINT,
	"temp_15_above_range" SMALLINT, --
	"soil_flux_range" SMALLINT,
	"soil_electronics_temp_range" SMALLINT,
	"soil_electronics_Vref_range" SMALLINT,
	"soil_spare_range" SMALLINT, --
	"Geiger_burst_count_range" SMALLINT,
	"Geiger_burst_time_range" SMALLINT,
	"barometric_temperature_range" SMALLINT, --
	"load_dcdc_voltage_input_range" SMALLINT,
	"load_dcdc_current_input_range" SMALLINT,
	"load_dcdc_current_output_range" SMALLINT,
	"load_dcdc_voltage_output_range" SMALLINT,
	"battery_charger_current_input_range" SMALLINT,
	"battery_charger_current_output_range" SMALLINT,
	"battery_charger_temperature_range" SMALLINT,
	"battery_charger_voltage_output_range" SMALLINT,
	"solar_dcdc_input_voltage_range" SMALLINT,
	"solar_dcdc_input_current_range" SMALLINT,
	"solar_charger_current_output_range" SMALLINT,
	"solar_charger_voltage_output_range" SMALLINT,
	"load_voltage_range" SMALLINT,
	"battery_voltage_range" SMALLINT,
	"battery_temperature_range" SMALLINT,
	"battery_protection_status_range" SMALLINT,
	"weatherproof_enclosure_temperature_range" SMALLINT,
	"power_supply_box_temperature_range" SMALLINT,
	"power_supply_humidity_range" SMALLINT,
	"V30_supply_fan_speed_range" SMALLINT,
	"V30_supply_fan_current_range" SMALLINT,
	"V30_supply_current_output_range" SMALLINT,
	"V30_supply_voltage_output_range" SMALLINT,
	"V30_supply_24V_supply_voltage_range" SMALLINT,
	"V30_converter_board_current_input_range" SMALLINT,
	"V30_converter_board_voltage_input_range" SMALLINT,
	"MOSFET_switches_status_range" SMALLINT,
	"protection_raw_voltage_range" SMALLINT,
	"protection_protected_voltage_range" SMALLINT,
	"protection_raw_input_current_range" SMALLINT,
	"protection_circuit_status_range" SMALLINT, --
	"mux_current_range" SMALLINT,
	"mux_temperature_range" SMALLINT,
	"Peet_wind_rate_range" SMALLINT,
	"Peet_wind_multl_range" SMALLINT,
	"Peet_windlo_range" SMALLINT,
	"Peet_wind_multh_range" SMALLINT,
	"Peet_windhi_range" SMALLINT,
	"Peet_vduce_range" SMALLINT,
	"Peet_winddir_range" SMALLINT,
	"Inspeed_wind_direction_range" SMALLINT,
	"Hydreon_current_range" SMALLINT,
	"Hydreon_temperature_range" SMALLINT,
	"Hydreon_range_setting_range" SMALLINT,
	"Hydreon_low_sense_range" SMALLINT,
	"Hydreon_medium_sense_range" SMALLINT,
	"Hydreon_high_sense_range" SMALLINT,
	"sky_sensor_current_range" SMALLINT,
	"sky_swiper_CW_current_range" SMALLINT,
	"sky_swiper_CCW_current_range" SMALLINT,
	"sky_dark_reading_range" SMALLINT,
	"sky_bright_reading_range" SMALLINT,
	"sky_IR_temperature_range" SMALLINT,
	"sky_sensor_status_range" SMALLINT,
	"sky_Hall_sensor_range" SMALLINT,
	"sway_X40_reading_range" SMALLINT,
	"sway_X1_reading_range" SMALLINT,
	"sway_Y1_reading_range" SMALLINT,
	"sway_Y40_reading_range" SMALLINT,
	"sway_sensor_temperature_range" SMALLINT,
	"sway_sensor_Vss_range" SMALLINT,
	"sway_Z_offset_range" SMALLINT,
	"sway_Z50_reading_range" SMALLINT,
	"lightning_current_range" SMALLINT,
	"lightning_UV_count_range" SMALLINT,
	"lightning_high_voltage_range" SMALLINT,
	"lightning_3001_lux_range" SMALLINT,
	"lightning_Skyscan_current_range" SMALLINT,
	"lightning_Skyscan_LEDs_range" SMALLINT,
	"lightning_Skyscan_flash_time_range" SMALLINT,
	"lightning_Skyscan_alarms_range" SMALLINT,
	"lightning_OPT101_baseline_range" SMALLINT,
	"lightning_OPT101_north_range" SMALLINT,
	"lightning_OPT101_south_range" SMALLINT,
	"lightning_OPT101_east_range" SMALLINT,
	"lightning_OPT101_west_range" SMALLINT,
	"lightning_OPT101_zenith_range" SMALLINT,
	"lightning_thunder_range" SMALLINT,
	"lightning_flag_range" SMALLINT,
	"lightning_UVA_UVB_range" SMALLINT,
	"lightning_OPT_temperature_range" SMALLINT, --
	"solar_box_temperature_range" SMALLINT,
	"solar_pyran_upper_byte_range" SMALLINT,
	"solar_pyran_middle_byte_range" SMALLINT,
	"solar_pyran_lower_byte_range" SMALLINT,
	"solar_par_upper_byte_range" SMALLINT,
	"solar_par_middle_byte_range" SMALLINT,
	"solar_par_lower_byte_range" SMALLINT,
	"solar_UV_upper_byte_range" SMALLINT,
	"solar_UV_middle_byte_range" SMALLINT,
	"solar_UV_lower_byte_range" SMALLINT,
	"solar_gold_grid_east_range" SMALLINT,
	"solar_gold_grid_west_range" SMALLINT,
	"solar_Decagon_horizontal_range" SMALLINT,
	"solar_Decagon_tilted_range" SMALLINT,
	"solar_frost_range" SMALLINT,
	"solar_bud_range" SMALLINT,
	"solar_globe_upper_byte_range" SMALLINT,
	"solar_globe_middle_byte_range" SMALLINT,
	"solar_globe_lower_byte_range" SMALLINT,
	"solar_current_range" SMALLINT,
	"solar_voltage_range" SMALLINT,
	"solar_IR_ground_temperature_range" SMALLINT, --
	"MetOne_LED_current_range" SMALLINT,
	"MetOne_wind_speed_average_range" SMALLINT,
	"MetOne_wind_speed_gust_range" SMALLINT, --
	"fuses_Arbcam_current_range" SMALLINT,
	"fuses_Arbcam_voltage_range" SMALLINT,
	"fuses_5_6_voltage_range" SMALLINT,
	"fuses_mux_current_range" SMALLINT,
	"fuses_lightning_current_range" SMALLINT,
	"fuses_solar_DAQ_current_range" SMALLINT,
	"fuses_fluxgate_current_range" SMALLINT,
	"fuses_triaxial_current_range" SMALLINT,
	"fuses_future_current_range" SMALLINT,
	"fuses_flag_range" SMALLINT,
	"fuses_warn_range" SMALLINT,
	"fuses_go_up_range" SMALLINT,
	"fuses_monitor_range" SMALLINT,
	"fuses_Arbcam_mode_range" SMALLINT,
	"fuses_fault_status_range" SMALLINT, --
	"power_solar_panel_current_range" SMALLINT,
	"power_solar_panel_voltage_range" SMALLINT,
	"power_battery_current_B_range" SMALLINT,
	"power_battery_voltage_B_range" SMALLINT,
	"power_current_into_5_6_range" SMALLINT,
	"power_voltage_into_5_6_range" SMALLINT,
	"power_5_6_load_current_range" SMALLINT,
	"power_5_6_load_voltage_range" SMALLINT,
	"power_box_temperature_B_range" SMALLINT,
	"power_Arbcam_dcdc_input_current_range" SMALLINT,
	"power_Arbcam_dcdc_input_voltage_range" SMALLINT,
	"power_Arbcam_current_range" SMALLINT,
	"power_Arbcam_voltage_range" SMALLINT,
	"power_battery_temperature_range" SMALLINT,
	"power_128K_battery_voltage_range" SMALLINT,
	"power_RTC_battery_voltage_range" SMALLINT,
	"power_RTD_30ft_temperature_range" SMALLINT,
	"power_hail_peak_range" SMALLINT,
	"power_hail_average_range" SMALLINT,
	"power_status_B_range" SMALLINT,
	"power_OVP_cycles_range" SMALLINT,
	"power_OVP_voltage_range" SMALLINT,
	"power_hail_sensor_temperature_range" SMALLINT,
	"power_hail_sensor_hits_range" SMALLINT,
	"power_box_humidity_range" SMALLINT, --
	"s_X1_range" SMALLINT,
	"s_X2_range" SMALLINT,
	"s_X3_range" SMALLINT,
	"s_X4_range" SMALLINT,
	"s_X5_range" SMALLINT,
	"s_X6_range" SMALLINT,
	"s_X7_range" SMALLINT,
	"s_X8_range" SMALLINT,
	"s_X9_range" SMALLINT,
	"s_X10_range" SMALLINT,
	"s_X11_range" SMALLINT,
	"s_X12_range" SMALLINT,
	"s_X13_range" SMALLINT,
	"s_X14_range" SMALLINT,
	"s_X15_range" SMALLINT,
	"s_X16_range" SMALLINT,
	"s_X17_range" SMALLINT,
	"s_X18_range" SMALLINT,
	"s_X19_range" SMALLINT,
	"s_X20_range" SMALLINT,
	"s_X21_range" SMALLINT,
	"s_X22_range" SMALLINT,
	"s_X23_range" SMALLINT,
	"s_X24_range" SMALLINT,
	"s_X25_range" SMALLINT,
	"s_X26_range" SMALLINT,
	"s_X27_range" SMALLINT,
	"s_X28_range" SMALLINT,
	"s_X29_range" SMALLINT,
	"s_X30_range" SMALLINT,
	"s_X31_range" SMALLINT,
	"s_X32_range" SMALLINT,
	"s_X33_range" SMALLINT,
	"s_X34_range" SMALLINT,
	"s_X35_range" SMALLINT,
	"s_X36_range" SMALLINT,
	"s_X37_range" SMALLINT,
	"s_X38_range" SMALLINT,
	"s_X39_range" SMALLINT,
	"s_X40_range" SMALLINT, --
	"s_Y1_range" SMALLINT,
	"s_Y2_range" SMALLINT,
	"s_Y3_range" SMALLINT,
	"s_Y4_range" SMALLINT,
	"s_Y5_range" SMALLINT,
	"s_Y6_range" SMALLINT,
	"s_Y7_range" SMALLINT,
	"s_Y8_range" SMALLINT,
	"s_Y9_range" SMALLINT,
	"s_Y10_range" SMALLINT,
	"s_Y11_range" SMALLINT,
	"s_Y12_range" SMALLINT,
	"s_Y13_range" SMALLINT,
	"s_Y14_range" SMALLINT,
	"s_Y15_range" SMALLINT,
	"s_Y16_range" SMALLINT,
	"s_Y17_range" SMALLINT,
	"s_Y18_range" SMALLINT,
	"s_Y19_range" SMALLINT,
	"s_Y20_range" SMALLINT,
	"s_Y21_range" SMALLINT,
	"s_Y22_range" SMALLINT,
	"s_Y23_range" SMALLINT,
	"s_Y24_range" SMALLINT,
	"s_Y25_range" SMALLINT,
	"s_Y26_range" SMALLINT,
	"s_Y27_range" SMALLINT,
	"s_Y28_range" SMALLINT,
	"s_Y29_range" SMALLINT,
	"s_Y30_range" SMALLINT,
	"s_Y31_range" SMALLINT,
	"s_Y32_range" SMALLINT,
	"s_Y33_range" SMALLINT,
	"s_Y34_range" SMALLINT,
	"s_Y35_range" SMALLINT,
	"s_Y36_range" SMALLINT,
	"s_Y37_range" SMALLINT,
	"s_Y38_range" SMALLINT,
	"s_Y39_range" SMALLINT,
	"s_Y40_range" SMALLINT, --
	"f_T1_range" SMALLINT,
	"f_X1_range" SMALLINT,
	"f_Y1_range" SMALLINT,
	"f_Z1_range" SMALLINT,
	"f_T2_range" SMALLINT,
	"f_X2_range" SMALLINT,
	"f_Y2_range" SMALLINT,
	"f_Z2_range" SMALLINT,
	"f_T3_range" SMALLINT,
	"f_X3_range" SMALLINT,
	"f_Y3_range" SMALLINT,
	"f_Z3_range" SMALLINT,
	"f_T4_range" SMALLINT,
	"f_X4_range" SMALLINT,
	"f_Y4_range" SMALLINT,
	"f_Z4_range" SMALLINT,
	"f_T5_range" SMALLINT,
	"f_X5_range" SMALLINT,
	"f_Y5_range" SMALLINT,
	"f_Z5_range" SMALLINT,
	"f_T6_range" SMALLINT,
	"f_X6_range" SMALLINT,
	"f_Y6_range" SMALLINT,
	"f_Z6_range" SMALLINT,
	"f_T7_range" SMALLINT,
	"f_X7_range" SMALLINT,
	"f_Y7_range" SMALLINT,
	"f_Z7_range" SMALLINT,
	"f_T8_range" SMALLINT,
	"f_X8_range" SMALLINT,
	"f_Y8_range" SMALLINT,
	"f_Z8_range" SMALLINT,
	"f_T9_range" SMALLINT,
	"f_X9_range" SMALLINT,
	"f_Y9_range" SMALLINT,
	"f_Z9_range" SMALLINT,
	"f_T10_range" SMALLINT,
	"f_X10_range" SMALLINT,
	"f_Y10_range" SMALLINT,
	"f_Z10_range" SMALLINT,
	"f_T11_range" SMALLINT,
	"f_X11_range" SMALLINT,
	"f_Y11_range" SMALLINT,
	"f_Z11_range" SMALLINT,
	"f_T12_range" SMALLINT,
	"f_X12_range" SMALLINT,
	"f_Y12_range" SMALLINT,
	"f_Z12_range" SMALLINT,
	"f_T13_range" SMALLINT,
	"f_X13_range" SMALLINT,
	"f_Y13_range" SMALLINT,
	"f_Z13_range" SMALLINT,
	"f_T14_range" SMALLINT,
	"f_X14_range" SMALLINT,
	"f_Y14_range" SMALLINT,
	"f_Z14_range" SMALLINT, --
	"fluxgate_current_range" SMALLINT,
	"fluxgate_temperature_range" SMALLINT,
	"fluxgate_xset_range" SMALLINT,
	"fluxgate_yset_range" SMALLINT,
	"fluxgate_zset_range" SMALLINT,
	"fluxgate_flag_range" SMALLINT, --
	"t_T1_range" SMALLINT,
	"t_X1_range" SMALLINT,
	"t_Y1_range" SMALLINT,
	"t_Z1_range" SMALLINT,
	"t_T2_range" SMALLINT,
	"t_X2_range" SMALLINT,
	"t_Y2_range" SMALLINT,
	"t_Z2_range" SMALLINT,
	"t_T3_range" SMALLINT,
	"t_X3_range" SMALLINT,
	"t_Y3_range" SMALLINT,
	"t_Z3_range" SMALLINT,
	"t_T4_range" SMALLINT,
	"t_X4_range" SMALLINT,
	"t_Y4_range" SMALLINT,
	"t_Z4_range" SMALLINT,
	"t_T5_range" SMALLINT,
	"t_X5_range" SMALLINT,
	"t_Y5_range" SMALLINT,
	"t_Z5_range" SMALLINT,
	"t_T6_range" SMALLINT,
	"t_X6_range" SMALLINT,
	"t_Y6_range" SMALLINT,
	"t_Z6_range" SMALLINT,
	"t_T7_range" SMALLINT,
	"t_X7_range" SMALLINT,
	"t_Y7_range" SMALLINT,
	"t_Z7_range" SMALLINT,
	"t_T8_range" SMALLINT,
	"t_X8_range" SMALLINT,
	"t_Y8_range" SMALLINT,
	"t_Z8_range" SMALLINT,
	"t_T9_range" SMALLINT,
	"t_X9_range" SMALLINT,
	"t_Y9_range" SMALLINT,
	"t_Z9_range" SMALLINT,
	"t_T10_range" SMALLINT,
	"t_X10_range" SMALLINT,
	"t_Y10_range" SMALLINT,
	"t_Z10_range" SMALLINT,
	"t_T11_range" SMALLINT,
	"t_X11_range" SMALLINT,
	"t_Y11_range" SMALLINT,
	"t_Z11_range" SMALLINT,
	"t_T12_range" SMALLINT,
	"t_X12_range" SMALLINT,
	"t_Y12_range" SMALLINT,
	"t_Z12_range" SMALLINT,
	"t_T13_range" SMALLINT,
	"t_X13_range" SMALLINT,
	"t_Y13_range" SMALLINT,
	"t_Z13_range" SMALLINT,
	"t_T14_range" SMALLINT,
	"t_X14_range" SMALLINT,
	"t_Y14_range" SMALLINT,
	"t_Z14_range" SMALLINT,
	"t_T15_range" SMALLINT,
	"t_X15_range" SMALLINT,
	"t_Y15_range" SMALLINT,
	"t_Z15_range" SMALLINT,
	"t_T16_range" SMALLINT,
	"t_X16_range" SMALLINT,
	"t_Y16_range" SMALLINT,
	"t_Z16_range" SMALLINT,
	"t_T17_range" SMALLINT,
	"t_X17_range" SMALLINT,
	"t_Y17_range" SMALLINT,
	"t_Z17_range" SMALLINT,
	"t_T18_range" SMALLINT,
	"t_X18_range" SMALLINT,
	"t_Y18_range" SMALLINT,
	"t_Z18_range" SMALLINT,
	"t_T19_range" SMALLINT,
	"t_X19_range" SMALLINT,
	"t_Y19_range" SMALLINT,
	"t_Z19_range" SMALLINT,
	"t_T20_range" SMALLINT,
	"t_X20_range" SMALLINT,
	"t_Y20_range" SMALLINT,
	"t_Z20_range" SMALLINT, --
	"triaxial_current_range" SMALLINT,
	"triaxial_volts_range" SMALLINT,
	"triaxial_temperature_range" SMALLINT, --
	"PurpleAir_dcdc_current_input_range" SMALLINT,
	"PurpleAir_dcdc_current_output_range" SMALLINT,
	"PurpleAir_dcdc_voltage_range" SMALLINT, --
	"Particles_dcdc_current_input_range" SMALLINT,
	"Particles_dcdc_current_output_range" SMALLINT,
	"Particles_dcdc_voltage_range" SMALLINT,
	"Particles_dcdc_temperature_range" SMALLINT,
	"Aux_box_fans_voltage_range" SMALLINT, --
	"Aux_B_dcdc_current_input_range" SMALLINT,
	"Aux_B_dcdc_current_output_range" SMALLINT,
	"Aux_B_dcdc_voltage_range" SMALLINT, --
	"Aux_A_dcdc_current_input_range" SMALLINT,
	"Aux_A_dcdc_current_output_range" SMALLINT,
	"Aux_A_dcdc_voltage_range" SMALLINT,
	"Aux_A_dcdc_temperature_range" SMALLINT,
	"Aux_A_spare_range" SMALLINT, --
	"Schumann_dcdc_current_input_range" SMALLINT,
	"Schumann_dcdc_current_output_range" SMALLINT,
	"Schumann_dcdc_voltage_range" SMALLINT, --
	"CFLUX_1_dcdc_current_input_range" SMALLINT,
	"CFLUX_1_dcdc_current_output_range" SMALLINT,
	"CFLUX_1_dcdc_voltage_range" SMALLINT,
	"CFLUX_spare_1_range" SMALLINT,
	"CFLUX_spare_2_range" SMALLINT, --
	"Aux_box_input_current_range" SMALLINT,
	"Aux_box_input_voltage_range" SMALLINT,
	"fiber_optic_link_dcdc_current_input_range" SMALLINT,
	"fiber_optic_link_dcdc_voltage_input_range" SMALLINT,
	"USB_jack_dcdc_current_input_range" SMALLINT,
	"USB_jack_dcdc_voltage_input_range" SMALLINT,
	"USB_dcdc_temperature_range" SMALLINT,
	"fans_current_range" SMALLINT,
	"fan_A_speed_range" SMALLINT,
	"fan_B_speed_range" SMALLINT,
	"fan_C_speed_range" SMALLINT,
	"Aux_box_humidity_range" SMALLINT,
	"Aux_box_fan_status_range" SMALLINT,
	"Aux_box_MOSFET_status_range" SMALLINT,
	"Aux_box_fuse_status_range" SMALLINT,
	"Aux_box_over_current_status_range" SMALLINT
	);